server:
  port: 9000

spring:
  boot:
    admin:
      client:
        url: "http://localhost:9004"
  application:
    name: ProviderA
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/libingteam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  profiles:
    active: core

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    health-check-url-path: actuator/health
    status-page-url-path: actuator/info

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  level:
    com.zjy: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
