spring:
  cache:
    ehcache:
      config: classpath:ehcache/ehcache-spring.xml
  redis:
      jedis:
        pool:
          max-active: 10
          max-idle: 10
          max-wait: 1000ms
  datasource:
      druid:
        driver-class-name: ${spring.datasource.driver-class-name}
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
        initial-size: 2
        max-active: 10
        min-idle: 2
        max-wait: 60000
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 200
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

