server:
  port: 9003

spring:
#  配置Spring Boot Admin管理相关信息
  boot:
    admin:
      client:
          url: "http://localhost:9004"

#配置bus相关消息
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#配置eureka相关信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    status-page-url-path: actuator/info
    health-check-url-path: actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


#logging:
#  level:
#  com.zjy: debug
